baseURL = "http://alfarizi008.github.io"
title = "Ghur08a"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Giovanni Alfarizi"
description = "Giovanni Alfarizi's personal website"
keywords = "blog,developer,personal"
info = ["Student",]
avatarURL = "images/me_pr.png"
#gravatar = "john.doe@example.com"
footerContent = "If sins had an odor, no one would be able to sit near me - Muhammad ibn Waasi' rahimahullah"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2020

# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/alfarizi008/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 2
url = "https://gitlab.com/alfarizi008/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/giovanni_fariz/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/giovanni-alfarizi/"

[[params.social]]
name = "Medium"
icon = "fa fa-medium"
weight = 5
url = "https://medium.com/@giovannifariz99"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 6
url = "http://alfarizi008.blogspot.com/"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Portfolio"
weight = 2
url = "portfolio/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

[languages.id]
languageName = ":indonesia:"
title = "Ghur08a"

[languages.id.params]
author = "Giovanni Alfarizi"
info = "Pelajar"
description = "Sítio pessoal de João Ninguém"
keywords = "blog,desenvolvedor,pessoal"
footerContent = "Jika dosa memiliki bau, maka tidak seorang pun yang akan duduk di dekat saya - Muhammad bin Waasi' rahimahullah"

[[languages.id.menu.main]]
name = "Postingan"
weight = 1
url = "posts/"

[[languages.id.menu.main]]
name = "Portfolio"
weight = 2
url = "portfolio/"

[[languages.id.menu.main]]
name = "Tentang"
weight = 3
url = "about/"
